# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jared R. Levin
email: jaredrlevin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm Jared. I'm a developer with a passion for baseball, indie music and technology. Professed (and proud) coffee snob with a love for traveling. Let's connect!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jarlev.github.io" # the base hostname & protocol for your site
twitter_username: jar_lev
github_username:  jarlev

# Build settings
markdown: kramdown
